  - name: Install docker
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  - name: Start docker service
    command: systemctl start docker

  - name: Add docker group
    group:
      name: docker
      state: present

  - name: Add user to docker group
    user:
      name: opc
      groups: docker
      append: yes

  - name: Install docker-compose
    #replace this url with the correct one depending on the architecture
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-armv7
      dest: /usr/local/bin/docker-compose

  - name: Change docker-compose permissions
    file:
      path: /usr/local/bin/docker-compose
      mode: u+x,g+x,o+x
